[filetype]

rules = [
	# Images
	{ mime = "image/*", fg = "yellow" },

	# Media
	{ mime = "{audio,video}/*", fg = "magenta" },

	# Archives
	{ mime = "application/*zip", fg = "green" },
	{ mime = "application/x-{tar,bzip*,7z-compressed,xz,rar,dmg}", fg = "green" },

	# Documents
	{ mime = "application/{pdf,doc,docx,rtf,vnd.*}", fg = "cyan" },

	# Empty files
	# { mime = "inode/x-empty", fg = "green" },

	# Special files
	{ name = "*", is = "orphan", bg = "red" },
	{ name = "*", is = "exec"  , fg = "blue" },

	# Fallback
	{ name = "*/", fg = "lightblue" }
]

